### ISSUE TITLE
Update for new Module Hierarchy

### ISSUE THREAD

**Issue by grebe** [freechipsproject/chisel-testers#174]
I have some `PeekPokeTester`s for rocket-chip `LazyModuleImp`s. Chisel has refactored what `Module` points to and added a whole hierarchy. I don't really understand what all the different modules are meant to be, but evidently `LazyModuleImp` is not a `Module` (I think it is an `ImplicitModule`?) so I can't use `PeekPokeTester`s on it anymore.

I think the fix for this is simple- wherever we have a `T <: Module` should be replaced with `T <: BaseModule` or `UserModule` or whatever the appropriate `Module` type is. @chick, do you know what the appropriate `Module` class is?

**Comment by chick** [comment]
@grebe I don't but I have played around with them a little bit so I'm not starting from scratch.
Is there any code I can look at before I try and answer
