### ISSUE TITLE
Make Treadle the Default Backend

### ISSUE THREAD

**Issue by seldridge** [freechipsproject/chisel-testers#273]
There are known issues with the FIRRTL interpreter backend. This proposes sidestepping all this by updating chisel-testers to use Treadle as it's default backend.

**Comment by johnsbrew** [comment]
https://github.com/freechipsproject/chisel-testers/blame/master/src/main/scala/chisel3/iotesters/TesterOptions.scala#L26

It seems it is already the case?

**Comment by chick** [comment]
Thanks for the pointer @johnsbrew
